In [2]:
import numpy as np
import matplotlib.pyplot as plt

1. Решите линейную систему:

In [7]:
A=np.array([ [1,2,3], [4,0,6], [7,8,9] ])
B=np.array([12,2,1])
np.linalg.solve(A,B)

array([-9.2       ,  0.9       ,  6.46666667])


2. Найдите псевдорешение:


In [10]:
A=np.array([ [1,2,-1], [3,-4,0],  [8,-5,2], [2,0,-5], [11,4,-7] ])
B=np.array([1,7,12,7,15])
np.linalg.lstsq(A,B)

C:\Users\imasl\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))


3. Сколько решений имеет линейная система:


In [18]:
A=np.array([ [1,2,3], [4,5,6], [7,8,9] ])
B=np.array([[2,5,1]])
C=np.concatenate((A,B.T), axis=1)
np.linalg.matrix_rank(A),np.linalg.matrix_rank(C)#нет решений

(2, 3)

4. Вычислите LU-разложение матрицы:

In [22]:
import scipy 
import scipy.linalg

In [25]:
A=np.array([ [1,2,3], [2,16,21], [4,28,73] ])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

print( np.dot(P,A) - np.dot(L,U) )

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ -2. -12. -52.]
 [  3.  26.  70.]
 [ -1. -14. -18.]]


In [26]:
B=np.array([12,2,1])
np.linalg.solve(A,B)

array([15.81018519, -1.47453704, -0.28703704])

5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1
8x – 5y + 2z = 12


In [3]:

A=np.array([ [1,2,-1], [8,-5,2]])
B=np.array([1,12])
np.linalg.lstsq(A,B)


C:\Users\imasl\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

6. Найдите одно из псевдорешений вырожденной системы:

In [10]:
A=np.array([ [1,2,3], [4,5,6], [7,8,9] ])
B=np.array([2,5,11])

Q, R = np.linalg.qr(A)

print (A)
print (Q)
print (R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [7]:
print(np.dot(Q,R))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [8]:
print(np.dot(np.transpose(Q),Q))

[[ 1.00000000e+00 -5.26517217e-16 -2.55176183e-16]
 [-5.26517217e-16  1.00000000e+00  3.37757775e-16]
 [-2.55176183e-16  3.37757775e-16  1.00000000e+00]]


In [12]:
R1=R[:2,:2]
B1=np.dot(np.transpose(Q),B)[:2]
print(R1)
print(B1)

[[-8.1240384  -9.6011363 ]
 [ 0.          0.90453403]]
[-1.21860576e+01  8.54871729e-15]


In [14]:
X1= np.linalg.solve(R1,B1)
X1

array([1.50000000e+00, 9.45096256e-15])

In [15]:
X=np.append(X1,0)
X

array([1.50000000e+00, 9.45096256e-15, 0.00000000e+00])