In [1]:
import numpy as np

In [3]:
E=np.identity(5)
np.linalg.inv(5*E) 

array([[ 0.2,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.2,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.2,  0. ,  0. ],
       [-0. , -0. , -0. ,  0.2, -0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.2]])

In [7]:
A=np.matrix('1 2 3; 4 0 6; 7 8 9')
A

matrix([[1, 2, 3],
        [4, 0, 6],
        [7, 8, 9]])

In [8]:
det=np.linalg.det(A)
det

59.999999999999986

In [9]:
AI=np.linalg.inv(A)
AI

matrix([[-0.8       ,  0.1       ,  0.2       ],
        [ 0.1       , -0.2       ,  0.1       ],
        [ 0.53333333,  0.1       , -0.13333333]])

In [10]:
A=np.matrix('1 5 0; 2 8 7; 7 1.5 3')
A

matrix([[1. , 5. , 0. ],
        [2. , 8. , 7. ],
        [7. , 1.5, 3. ]])

In [11]:
det=np.linalg.det(A)
det

228.49999999999986